name: Run Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  docs:
    name: Building docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docs
          load: true
          tags: sphinxdoc:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: docker run --rm -v ./:/docs sphinxdoc:latest

  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - run: pip install --user black

      - name: Cache linting tools
        uses: actions/cache@v3
        with:
          key: python-3.11-pip-tools
          path: |
            /usr/local/bin/uncrustify

      - name: Clone and install linting tools
        run: |
          black --version
          gcc --version
          git clone -b v0.8.19 --depth 1 https://github.com/citusdata/tools.git ../tools
          sudo make -C ../tools install
          install_uncrustify
          rm -rf uncrustify*

      - name: Check code formatting and banned function
        run: |
          make lint
